
<div class="hero-banner-content d-flex" data-bind="scope: 'hero-banner'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/javascript">
    require(['slider-js'], function(slider) {
    });
</script>

<script type="text/x-magento-init">
{
    ".hero-banner-content": {
        "Magento_Ui/js/core/app": {
            "components": {
                "hero-banner": {
                    "component": "Magento_Theme/js/herobanner",
                    "template": "Magento_Theme/herobanner-tpl"
                }
            }
        }
    }
}
</script>

