    <div class="hero-banner-content d-flex">
        <div style="width: 70%;" class="left-slider ">
            <div class="slick-slider">
                <div class="item"><img src="<?= $block->getViewFileUrl('images/Slider.png'); ?>"" /></div>
                <div class=" item"><img src="<?= $block->getViewFileUrl('images/Slider.png'); ?>"" /></div>
                <div class=" item"><img src="<?= $block->getViewFileUrl('images/Slider.png'); ?>"" /></div>
                <div class=" item"><img src="<?= $block->getViewFileUrl('images/Slider.png'); ?>"" /></div>
                <div class=" item"><img src="<?= $block->getViewFileUrl('images/Slider.png'); ?>"" /></div>
            </div>
        </div>
        <div  style=" width: 30%;" class="right-imgs">
                    <img style="height: calc(50% - 1.2rem);" src="<?= $block->getViewFileUrl('images/herobanner-1.png'); ?>"" alt="">
            <img  style=" height: calc(50% - 1.2rem);" src="<?= $block->getViewFileUrl('images/herobanner-2.png'); ?>"" alt="">
        </div>
    </div>
    <div class=" selling-feature">
                    <div class="feature-content d-flex">
                        <div class="logo d-flex">
                            <img src="<?= $block->getViewFileUrl('images/icons/1.png'); ?>"" alt="">
                                </div>
                                 <div class=" content">
                            <h4 class="title">Free Delivery</h4>
                            <p class="suptitle">For all orders over 1,000,000đ</p>
                        </div>
                    </div>
                    <span></span>
                    <div class="feature-content d-flex">
                        <div class="logo d-flex">
                            <img src="<?= $block->getViewFileUrl('images/icons/2.png'); ?>"" alt="">
                                </div>
                                <div class=" content">
                            <h4 class="title">Authentic Products</h4>
                            <p class="suptitle">Legitiamte origin</p>
                        </div>
                    </div>
                    <span></span>
                    <div class="feature-content d-flex">
                        <div class="logo d-flex">
                            <img src="<?= $block->getViewFileUrl('images/icons/3.png'); ?>"" alt="">
                                </div>
                                 <div class=" content">
                            <h4 class="title">Secure Payment</h4>
                            <p class="suptitle">100% secure payment</p>
                        </div>
                    </div>
                    <span></span>
                    <div class="feature-content d-flex">
                        <div class="logo d-flex">
                            <img src="<?= $block->getViewFileUrl('images/icons/4.png'); ?>"" alt="">
                            </div>
                            <div class=" content">
                            <h4 class="title">24/7 support</h4>
                            <p class="suptitle">Dedicated support</p>
                        </div>
                    </div>
                </div>