<div class="custom-tab">
    <div class="tabsnav-wrap d-flex">
        <h3>NEWs</h3>
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Review Product</a></li>
            <li><a data-toggle="tab" href="#tab2">Tips & Tricks</a></li>
            <li><a data-toggle="tab" href="#tab3">Promotions</a></li>
            <li><a data-toggle="tab" href="#tab4">View All</a></li>
        </ul>
    </div>
    <div class="tab-content">
        <div id="tab1" class="tab-pane in active">
            <a href="#" class="block">
                <img src="<?= $block->getViewFileUrl("images/Rectangle 2315.png") ?>" alt="">
                <p class="text">How To Make A Fresh Juice Blended For Your Family</p>
                <span>Organic</span>
            </a href="#">
            <a href="#" class="block">
                <img src="<?= $block->getViewFileUrl("images/Rectangle 2316.png") ?>" alt="">
                <p class="text">How To Make A Fresh Juice Blended For Your Family</p>
                <span>Organic</span>
            </a href="#">
            <a href="#" class="block">
                <img src="<?= $block->getViewFileUrl("images/Rectangle 2317.png") ?>" alt="">
                <p class="text">How To Make A Fresh Juice Blended For Your Family</p>
                <span>Organic</span>
            </a href="#">
            <a href="#" class="block">
                <img src="<?= $block->getViewFileUrl("images/Rectangle 2318.png") ?>" alt="">
                <p class="text">How To Make A Fresh Juice Blended For Your Family</p>
                <span>Organic</span>
            </a href="#">
        </div>
        <div id="tab2" class="tab-pane">
            <h1>tab2 act</h1>
        </div>
        <div id="tab3" class="tab-pane">
            <h1>tab3 act</h1>
        </div>
        <div id="tab4" class="tab-pane">
            <h1>tab4 act</h1>
        </div>
    </div>
</div>