<div class="row">
    <div class="col col-6 col-md-12">
        <div class="pro-banner-content">
            <img src="<?= $block->getViewFileUrl('Magento_Theme/images/banner-2.png'); ?>"" alt="">
        </div>
    </div>
    <div class="col col-6 col-md-12">
        <div class="pro-banner-content">
            <img src="<?= $block->getViewFileUrl('Magento_Theme/images/banner-3.png'); ?>"" alt="">
        </div>
    </div>
</div>