 <div class="product-slick-slider">
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Multi Cooker 9 Liters</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                1000 <span>$</span>
            </div>
            <div class="new-price">
                800 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (1).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Sharp Dynabook VE1.5</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                100 <span>$</span>
            </div>
            <div class="new-price">
                99 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (2).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>NewZealand Cherry</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                40 <span>$</span>
            </div>
            <div class="new-price">
                25 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (3).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Sharp Face Mask FDA Certified</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                10 <span>$</span>
            </div>
            <div class="new-price">
                7 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (4).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Sharp Healsio AX-1700</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                1000 <span>$</span>
            </div>
            <div class="new-price">
                999 <span>$</span>
            </div>
        </div>
    </div>

    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Multi Cooker 9 Liters</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                1000 <span>$</span>
            </div>
            <div class="new-price">
                800 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (1).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Sharp Dynabook VE1.5</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                100 <span>$</span>
            </div>
            <div class="new-price">
                99 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (2).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>NewZealand Cherry</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                40 <span>$</span>
            </div>
            <div class="new-price">
                25 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (3).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Sharp Face Mask FDA Certified</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                10 <span>$</span>
            </div>
            <div class="new-price">
                7 <span>$</span>
            </div>
        </div>
    </div>
    <div class="item m-4">
        <div class="product-img">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/Rectangle 9 (4).png'); ?>"" />
        </div>
        <div class="product-content">
            <div class="product-name">
                <p>Sharp Healsio AX-1700</p>
            </div>
            <div class="product-rate">
                *****
            </div>
            <div class="old-price">
                1000 <span>$</span>
            </div>
            <div class="new-price">
                999 <span>$</span>
            </div>
        </div>
    </div>
 </div>