<div class="category-content">
    <div class="row">
        <div class="col col-4">
            <div class="box-content">
                <a href="#">
                    <img src="<?= $block->getViewFileUrl('images/Rectangle 7.png'); ?>"" alt="">
                    <div class=" text">
                        <h3>Television</h3>
                        <div class="desc">
                            <p>Smart TV</p>
                            <p>4k Ultra HD</p>
                            <p>OLED</p>
                            <p>Accessories</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col col-4">
            <div class="box-content">
                <a href="#">
                    <img src="<?= $block->getViewFileUrl('images/Rectangle 7-1.png'); ?>"" alt="">
                        <div class=" text">
                    <h3>Personal Care</h3>
                    <div class="desc">
                        <p>Face Mask</p>
                        <p>Face Shield</p>
                    </div>
            </div>
            </a>
        </div>
    </div>
<div class="col col-4">
    <div class="box-content">
        <a href="#">
            <img src="<?= $block->getViewFileUrl('images/Rectangle 7-2.png'); ?>"" alt="">
                    <div class=" text">
            <h3>Smlal Appliances</h3>
            <div class="desc">
                <p>Microwave oven</p>
                <p>Air Fryer</p>
                <p>Rice cooker</p>
            </div>
    </div>
    </a>
</div>
</div>
</div>

<div class="row 2">
    <div class="col col-4">
        <div class="box-content">
            <a href="#">
                <img src="<?= $block->getViewFileUrl('images/Rectangle 7-3.png'); ?>"" alt="">
                    <div class=" text">
                <h3>Consumer Goods</h3>
                <div class="desc">
                    <p>Home Care</p>
                    <p>Hygienic Care</p>
                    <p>Insect treatment</p>
                </div>
        </div>
        </a>
    </div>
</div>
<div class="col col-4">
    <div class="box-content">
        <a href="#">
            <img src="<?= $block->getViewFileUrl('images/Rectangle 7-4.png'); ?>"" alt="">
                        <div class=" text">
            <h3>Food & Drink</h3>
            <div class="desc">
                <p>Fruit</p>
                <p>Confectionary</p>
                <p>Beverage</p>
                <p>Seasoning</p>
            </div>
    </div>
    </a>
</div>
</div>
<div class="col col-4">
    <div class="box-content">
        <a href="#">
            <img src="<?= $block->getViewFileUrl('images/Rectangle 7-5.png'); ?>"" alt="">
                    <div class=" text">
            <h3>Dietaru Supplement</h3>
    </div>
    </a>
</div>
</div>
</div>
</div>
<style>
    .box-content .text {
        padding: 16px;
    }
</style>