<div class="main-footer-content">
    <div class="row">
        <div class="col-3">
            <div class="col-content">
                <h3 class="title">QUICK LINKs</h3>
                <ul class="links">
                    <li><a href="#">Terms & Conditions</a></li>
                    <li><a href="#">Privacy Policies</a></li>
                    <li><a href="#">Delivery - Return - Warranty</a></li>
                    <li><a href="#">Payment Methods</a></li>
                    <li><a href="#">Loyalty Program</a></li>
                </ul>
            </div>
        </div>

        <div class="col-3">
            <div class="col-content">
                <h3 class="title">COMPANY</h3>
                <ul class="links">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">FAQs</a></li>
                </ul>
                <div class="card-type d-flex flex-wrap">
                    <img style="width: 30%" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/payment/pay 1.png'); ?>"" alt="">
                    <img style="width: 30%" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/payment/pay 2.png'); ?>"" alt="">
                    <img style="width: 50%" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/payment/pay 3.png'); ?>"" alt="">
                </div>
            </div>
        </div>

        <div class="col-3">
            <div class="col-content">
                <h3 class="title">Follow Us</h3>
                <ul class="links">
                    <li><a href="#">FB</a></li>
                    <li><a href="#">Youtube</a></li>
                </ul>
                <div class="Our Mobile Apps">
                    <a style="max-width: 120px; display: block; background-color: black; color:white;" href="">
                        <div class="logo">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/apple.png'); ?>"" alt="">
                        </div>
                        <div class="text">
                            <span>Download on the</span>
                            <p>App Store</p>
                        </div>
                    </a>

                    <a style="max-width: 120px; display: block; background-color: black; color:white;" href="">
                        <div class="logo">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/ggplay.png'); ?>"" alt="">
                        </div>
                        <div class="text">
                            <span>Get It On</span>
                            <p>Google Play</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>

        <div class="col-3">
            <div class="col-content">
                <h3 class="title">CÔNG TY ĐIỆN TỬ SHARP VIỆT NAM</h3>
                <ul class="links">
                    <li><p>Địa chỉ: T5-B03 & T5-B03.09, Lầu 3 Masteri Thảo Điền</p></li>
                    <li><p>159 Xa lộ Hà Nội, Phường Thảo Điền, TP. Thủ Đức, TP. Hồ Chí Minh, Việt Nam</p></li>
                    <li><p>Email: cskh@cororolife.vn</p></li>
                    <li><p>MST: 0308159258 Do Sở kế hoạch Đầu tư TP.HCM cấp ngày 13/3/2009</p></li>
                    <li><img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/Mask Group.png'); ?>"" alt=""></li>
                </ul>
            </div>
        </div>
    </div>
</div>